//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTicaretProje
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALISVERISSEPETI
    {
        public int sepetID { get; set; }
        public int urunID { get; set; }
        public string kullaniciID { get; set; }
    
        public virtual URUNLER URUNLER { get; set; }
    }
}
