//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTicaretProje
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class projectMVCDBEntities : DbContext
    {
        public projectMVCDBEntities()
            : base("name=projectMVCDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ALISVERISSEPETI> ALISVERISSEPETI { get; set; }
        public virtual DbSet<ANAKATEGORİ> ANAKATEGORİ { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<BANKALAR> BANKALAR { get; set; }
        public virtual DbSet<KAMPANYALAR> KAMPANYALAR { get; set; }
        public virtual DbSet<KARGO> KARGO { get; set; }
        public virtual DbSet<KATEGORILER> KATEGORILER { get; set; }
        public virtual DbSet<MARKALAR> MARKALAR { get; set; }
        public virtual DbSet<ODEMESECENEKLER> ODEMESECENEKLER { get; set; }
        public virtual DbSet<OZELLIKDETAY> OZELLIKDETAY { get; set; }
        public virtual DbSet<SIPARISLER> SIPARISLER { get; set; }
        public virtual DbSet<SLIDER> SLIDER { get; set; }
        public virtual DbSet<URUNLER> URUNLER { get; set; }
        public virtual DbSet<URUNOZELLIKLER> URUNOZELLIKLER { get; set; }
    }
}
