//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTicaretProje
{
    using System;
    using System.Collections.Generic;
    
    public partial class URUNOZELLIKLER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public URUNOZELLIKLER()
        {
            this.OZELLIKDETAY = new HashSet<OZELLIKDETAY>();
        }
    
        public int ozellikID { get; set; }
        public string ozellikAd { get; set; }
        public Nullable<int> anakategoriID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OZELLIKDETAY> OZELLIKDETAY { get; set; }
    }
}
