//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTicaretProje
{
    using System;
    using System.Collections.Generic;
    
    public partial class URUNLER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public URUNLER()
        {
            this.ALISVERISSEPETI = new HashSet<ALISVERISSEPETI>();
            this.KAMPANYALAR = new HashSet<KAMPANYALAR>();
            this.OZELLIKDETAY = new HashSet<OZELLIKDETAY>();
            this.SIPARISLER = new HashSet<SIPARISLER>();
        }
    
        public int urunID { get; set; }
        public int kategoriID { get; set; }
        public int markaID { get; set; }
        public string UrunAdi { get; set; }
        public string urunAciklama { get; set; }
        public Nullable<decimal> urunFiyat { get; set; }
        public Nullable<decimal> urunAlisFiyati { get; set; }
        public string urunResimYol { get; set; }
        public Nullable<System.DateTime> BaslangicTarihi { get; set; }
        public Nullable<System.DateTime> BitisTarihi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ALISVERISSEPETI> ALISVERISSEPETI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KAMPANYALAR> KAMPANYALAR { get; set; }
        public virtual KATEGORILER KATEGORILER { get; set; }
        public virtual MARKALAR MARKALAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OZELLIKDETAY> OZELLIKDETAY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIPARISLER> SIPARISLER { get; set; }
    }
}
